FROM nginx
COPY ./configurations/nginx/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /opt/services/user-portfolio-service/src/static
COPY ./configurations/nginx/static /opt/services/user-portfolio-service/src/static

