# Generated by Django 4.2.6 on 2025-08-25 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalHoldingThreshold",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "holding_type",
                    models.CharField(
                        help_text="Type/category of holding (e.g., STOCK, ETF)",
                        max_length=50,
                    ),
                ),
                (
                    "holding_id",
                    models.CharField(
                        help_text="Identifier of the holding (ticker symbol or internal ID)",
                        max_length=100,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        help_text="Position side this threshold applies to (long/short)",
                        max_length=10,
                    ),
                ),
                (
                    "threshold_type",
                    models.CharField(
                        choices=[
                            ("profit_target", "Profit Target"),
                            ("stop_loss", "Stop Loss"),
                        ],
                        help_text="Type of threshold rule (Profit Target/Stop Loss)",
                        max_length=20,
                    ),
                ),
                (
                    "target_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Percentage threshold for this rule",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Absolute value threshold for this rule",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Status of the rule",
                        max_length=8,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("dealer", "Dealer"),
                        ],
                        default="user",
                        help_text="Origin of the rule (User/Admin/Dealer)",
                        max_length=10,
                    ),
                ),
                ("effective_from", models.DateTimeField(blank=True, editable=False)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_notification_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Holding Threshold",
                "verbose_name_plural": "historical Holding Thresholds",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HoldingThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "holding_type",
                    models.CharField(
                        help_text="Type/category of holding (e.g., STOCK, ETF)",
                        max_length=50,
                    ),
                ),
                (
                    "holding_id",
                    models.CharField(
                        help_text="Identifier of the holding (ticker symbol or internal ID)",
                        max_length=100,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        help_text="Position side this threshold applies to (long/short)",
                        max_length=10,
                    ),
                ),
                (
                    "threshold_type",
                    models.CharField(
                        choices=[
                            ("profit_target", "Profit Target"),
                            ("stop_loss", "Stop Loss"),
                        ],
                        help_text="Type of threshold rule (Profit Target/Stop Loss)",
                        max_length=20,
                    ),
                ),
                (
                    "target_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Percentage threshold for this rule",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Absolute value threshold for this rule",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Status of the rule",
                        max_length=8,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("dealer", "Dealer"),
                        ],
                        default="user",
                        help_text="Origin of the rule (User/Admin/Dealer)",
                        max_length=10,
                    ),
                ),
                ("effective_from", models.DateTimeField(auto_now_add=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_notification_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Holding Threshold",
                "verbose_name_plural": "Holding Thresholds",
                "db_table": "holding_threshold",
                "indexes": [
                    models.Index(
                        fields=["holding_type", "holding_id"],
                        name="holding_thr_holding_846fc3_idx",
                    ),
                    models.Index(
                        fields=["holding_type", "holding_id", "side"],
                        name="holding_thr_holding_8b385c_idx",
                    ),
                    models.Index(
                        fields=["holding_type", "holding_id", "threshold_type"],
                        name="holding_thr_holding_80bff5_idx",
                    ),
                    models.Index(
                        condition=models.Q(("status", "active")),
                        fields=["holding_type", "holding_id", "side", "threshold_type"],
                        name="idx_holding_threshold_active",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="holdingthreshold",
            constraint=models.UniqueConstraint(
                fields=(
                    "holding_type",
                    "holding_id",
                    "side",
                    "threshold_type",
                    "target_pct",
                    "status",
                ),
                name="uniq_holding_threshold",
            ),
        ),
        migrations.AddField(
            model_name="historicalholdingthreshold",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
