# Generated by Django 4.2.6 on 2025-09-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_historicalholdingthreshold_holdingthreshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalholdingthreshold',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserportfoliothreshold',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holdingthreshold',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userportfoliothreshold',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
