# Generated by Django 4.2.6 on 2025-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_historicalholdingthreshold_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalholdingthreshold',
            name='target_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage threshold (e.g. 12.50%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalholdingthreshold',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Absolute value threshold in INR (up to ~1000 crore)', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserportfoliothreshold',
            name='target_pct',
            field=models.DecimalField(decimal_places=2, help_text='Percentage threshold (e.g. 12.50%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicaluserportfoliothreshold',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Absolute value threshold in INR (up to ~1000 crore)', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='holdingthreshold',
            name='target_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage threshold (e.g. 12.50%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='holdingthreshold',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Absolute value threshold in INR (up to ~1000 crore)', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='userportfoliothreshold',
            name='target_pct',
            field=models.DecimalField(decimal_places=2, help_text='Percentage threshold (e.g. 12.50%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userportfoliothreshold',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Absolute value threshold in INR (up to ~1000 crore)', max_digits=11, null=True),
        ),
    ]
