# Generated by Django 4.2.6 on 2025-09-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_historicalholdingthreshold_target_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalholdingthreshold',
            name='target_pct',
            field=models.FloatField(blank=True, help_text='Percentage threshold (e.g. 12.50%)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalholdingthreshold',
            name='target_value',
            field=models.FloatField(blank=True, help_text='Absolute value threshold in INR (up to ~1000 crore)', null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserportfoliothreshold',
            name='target_pct',
            field=models.FloatField(blank=True, help_text='Percentage threshold (e.g. 12.50%)', null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserportfoliothreshold',
            name='target_value',
            field=models.FloatField(blank=True, help_text='Absolute value threshold in INR (up to ~1000 crore)', null=True),
        ),
        migrations.AlterField(
            model_name='holdingthreshold',
            name='target_pct',
            field=models.FloatField(blank=True, help_text='Percentage threshold (e.g. 12.50%)', null=True),
        ),
        migrations.AlterField(
            model_name='holdingthreshold',
            name='target_value',
            field=models.FloatField(blank=True, help_text='Absolute value threshold in INR (up to ~1000 crore)', null=True),
        ),
        migrations.AlterField(
            model_name='userportfoliothreshold',
            name='target_pct',
            field=models.FloatField(blank=True, help_text='Percentage threshold (e.g. 12.50%)', null=True),
        ),
        migrations.AlterField(
            model_name='userportfoliothreshold',
            name='target_value',
            field=models.FloatField(blank=True, help_text='Absolute value threshold in INR (up to ~1000 crore)', null=True),
        ),
    ]
