# Generated by Django 4.2.6 on 2025-09-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_historicalholdingthreshold_target_pct_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holdingthreshold',
            name='uniq_holding_threshold',
        ),
        migrations.RemoveConstraint(
            model_name='userportfoliothreshold',
            name='uniq_threshold_per_portfolio',
        ),
    ]
