# Generated by Django 4.2.6 on 2025-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_remove_holdingthreshold_uniq_holding_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalholdingthreshold',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('processing', 'Processing')], default='active', help_text='Status of the rule', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaluserportfoliothreshold',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('processing', 'Processing')], default='active', help_text='Status of the rule', max_length=20),
        ),
        migrations.AlterField(
            model_name='holdingthreshold',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('processing', 'Processing')], default='active', help_text='Status of the rule', max_length=20),
        ),
        migrations.AlterField(
            model_name='userportfoliothreshold',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('processing', 'Processing')], default='active', help_text='Status of the rule', max_length=20),
        ),
    ]
