apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user-portfolio-service-beat-worker-blue-green.yaml
  - user-portfolio-service-ngnix-uat-blue-green.yaml
  - user-portfolio-service-uat-blue-green.yaml
