# Generated by Django 4.2.6 on 2023-10-26 19:17

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('symbol', models.CharField(max_length=30)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'db_table': 'holding',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source', models.CharField(choices=[('user', 'user'), ('portfolio', 'portfolio')], max_length=20)),
                ('target', models.CharField(choices=[('user', 'user'), ('portfolio', 'portfolio')], max_length=20)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('type', models.CharField(choices=[('cash_ingested', 'cash_ingested'), ('cash_missing', 'cash_missing')], max_length=20)),
                ('current_state', models.CharField(choices=[('pending', 'pending'), ('partial_complete', 'partial_complete'), ('complete', 'complete')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
