# Generated by Django 4.2.6 on 2023-10-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='current_state',
            field=models.CharField(choices=[('pending', 'pending'), ('partial_complete', 'partial_complete'), ('complete', 'complete')], default='complete', max_length=20),
        ),
    ]
