# Generated by Django 4.2.6 on 2023-11-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0003_alter_transaction_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='buy_avg_price',
            field=models.FloatField(default=0),
        ),
    ]
