# Generated by Django 4.2.6 on 2023-11-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0004_holding_buy_avg_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='buy_avg_price',
            new_name='avg_buy_price',
        ),
    ]
