# Generated by Django 4.2.6 on 2024-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0005_rename_buy_avg_price_holding_avg_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('cash_ingested', 'cash_ingested'), ('cash_missing', 'cash_missing'), ('uninvested', 'uninvested'), ('cash_removal', 'cash_removal')], max_length=20),
        ),
    ]
