# Generated by Django 4.2.6 on 2024-10-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0007_position_position_basket_symbol_unique_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='avg_buy_price',
        ),
    ]
