# Generated by Django 4.2.6 on 2024-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0008_remove_position_avg_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
    ]
