"""
Django settings for user_portfolio project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import logging
import os
from pathlib import Path
from kombu import Queue, Exchange

from kombu.utils.url import safequote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uhny#ws=9mgm&(_+)rowkznh0v8m$%%c9$-0l&_u&k&h28nvb1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

BASE_URL = os.environ.get('BASE_URL')
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django_celery_results',
    'django_celery_beat',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'apps.portfolio',
    'apps.holdings',
    'apps.alerts',
    'health_check',
    'health_check.cache',
    'simple_history',
    'django_extensions'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'log_request_id.middleware.RequestIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middlewares.request.RequestMiddleWare',
    'middlewares.response.ResponseMiddleWare',
    'middlewares.exception.ExceptionMiddleWare',
    'middlewares.log.RequestResponseLogMiddleware',
    'middlewares.tenant.TenantMiddleware',
]

ROOT_URLCONF = 'user_portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'multitenant.tenant_context.tenant_selector'
            ],
        },
    },
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = ['accept',
                      'accept-encoding',
                      'authorization',
                      'content-type',
                      'dnt',
                      'origin',
                      'user-agent',
                      'x-csrftoken',
                      'x-requested-with',
                      'timestamp',
                      'X-Tenant-ID']

WSGI_APPLICATION = 'user_portfolio.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

TENANT_DATABASES = {
    # "demo": {
    #     "ENGINE": 'django.db.backends.postgresql_psycopg2',
    #     "NAME": os.environ.get("DEMO_USER_PORTFOLIO_DB_NAME", ""),
    #     "USER": os.environ.get("DEMO_USER_PORTFOLIO_DB_USER", ""),
    #     "PASSWORD": os.environ.get("DEMO_USER_PORTFOLIO_DB_PASSWORD", ""),
    #     "HOST": os.environ.get("DEMO_USER_PORTFOLIO_DB_HOST", ""),
    #     "PORT": os.environ.get("DEMO_USER_PORTFOLIO_DB_PORT", "")
    # },
    # "hdfc": {
    #     "ENGINE": 'django.db.backends.postgresql_psycopg2',
    #     "NAME": os.environ.get("HDFC_DB_NAME", ""),
    #     "USER": os.environ.get("HDFC_DB_USER", ""),
    #     "PASSWORD": os.environ.get("HDFC_DB_PASSWORD", ""),
    #     "HOST": os.environ.get("HDFC_DB_HOST", ""),
    #     "PORT": os.environ.get("HDFC_DB_PORT", "")
    # },
    # "hdfcir": {
    #     "ENGINE": 'django.db.backends.postgresql_psycopg2',
    #     "NAME": os.environ.get("HDFCIR_DB_NAME", ""),
    #     "USER": os.environ.get("HDFCIR_DB_USER", ""),
    #     "PASSWORD": os.environ.get("HDFCIR_DB_PASSWORD", ""),
    #     "HOST": os.environ.get("HDFCIR_DB_HOST", ""),
    #     "PORT": os.environ.get("HDFCIR_DB_PORT", "")
    # },
    "ysl": {
        "ENGINE": 'django.db.backends.postgresql_psycopg2',
        "NAME": os.environ.get("YSL_DB_NAME", ""),
        "USER": os.environ.get("YSL_DB_USER", ""),
        "PASSWORD": os.environ.get("YSL_DB_PASSWORD", ""),
        "HOST": os.environ.get("YSL_DB_HOST", ""),
        "PORT": os.environ.get("YSL_DB_PORT", "")
    }
}

DATABASES = {
    'default': {
        "ENGINE": 'django.db.backends.postgresql_psycopg2',
        "NAME": os.environ.get("USER_PORTFOLIO_DB_NAME"),
        "USER": os.environ.get("USER_PORTFOLIO_DB_USER"),
        "PASSWORD": os.environ.get("USER_PORTFOLIO_DB_PASSWORD"),
        "HOST": os.environ.get("USER_PORTFOLIO_DB_HOST"),
        "PORT": os.environ.get("USER_PORTFOLIO_DB_PORT"),
    },
    **TENANT_DATABASES,
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
STATIC_ROOT = str(BASE_DIR) + '/static/'
MEDIA_ROOT = str(BASE_DIR) + '/media/'
STATIC_DIR = 'nginx/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

celery_log_config = {
    "version": 1,
    "propogate": False,
    "disable_existing_loggers": False,
    "formatters": {
        "celeryTask": {
            "()": "celery.app.log.TaskFormatter",
            "fmt": "[%(asctime)s] abc %(levelname)s [%(task_id)s] [%(processName)s][%(funcName)s][%(name)s:%(lineno)s] "
                   "%(""message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": 'logging.StreamHandler',
            "formatter": "celeryTask",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
            'propagate': False,
        }
    },
}


LOGGING = {
    'version': 1,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'request_id': {
            '()': 'log_request_id.filters.RequestIDFilter'
        },
    },
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s.%(msecs)03d] %(levelname)s [%(request_id)s] [%(name)s:%("
                      "lineno)s] %(""message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'filters': ['request_id'],
            'formatter': 'verbose',
        },
        'application': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'when': 'midnight',
            'backupCount': 3,
            'filename': 'logs/user_portfolio.log',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
        'worker': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'when': 'midnight',
            'backupCount': 3,
            'filename': 'logs/worker.log',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console', 'application'],
            'level': 'INFO',  # change debug level as appropiate
            'propagate': False,
        },
        'django.db.backends': {
            'level': 'INFO',
            'handlers': ['console', 'application'],
        },
        'celery': {
            'handlers': ['worker', 'console'],
            'level': 'INFO',
        },
        'apps': {
            'handlers': ['console', 'application'],
            'level': 'INFO',
        },
        'apps.tenant': {
            'handlers': ['console', 'application'],
            'level': 'INFO',
            'propagate': False,
        }
    }
}

CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')
BROKER_URL = os.environ.get('BROKER_URL')
CACHE_URL = os.environ.get('CACHE_URL')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": CACHE_URL,
    }
}

# Define prefix
prefix = os.environ.setdefault("DJANGO_SETTINGS_MODULE", "configurations.local").split(".")[-1]
APP_PREFIX = "user-portfolio"
APP_NAME = 'user_portfolio'

# Celery tasks
PHASE_DETAIL_CALLBACK = 'phase_detail_callback'
MONITORING = 'monitoring'
MONITOR_BASKET = 'monitor_basket'
MONITOR_ORDER = 'monitor_order'
SCHEDULER_PORTFOLIO_MONITORING = 'scheduler_portfolio_monitoring'
SCHEDULER_PORTFOLIO_MONITORING_ = 'scheduler_portfolio_monitoring_'
MONITOR_PORTFOLIO_ALERTS = 'monitor_portfolio_alerts'
SCHEDULER_HOLDING_MONITORING = 'scheduler_holding_monitoring'
SCHEDULER_HOLDING_MONITORING_ = 'scheduler_holding_monitoring_'
MONITOR_HOLDING_THRESHOLD_ALERTS = 'monitor_holding_threshold_alerts'
SEND_INVESTMENT_SUCCEEDED_EVENT = 'send_investment_succeeded_event'
SEND_WITHDRAWAL_SUCCEEDED_EVENT = 'send_withdrawal_succeeded_event'
SEND_LOSS_LIMIT_UPDATED_NOTIFICATION = 'send_loss_limit_updated_notification'

# Celery queues
PHASE_DETAIL_CALLBACK_QUEUE = f"{APP_NAME}_{PHASE_DETAIL_CALLBACK}_{prefix}"
MONITORING_QUEUE = f"{APP_NAME}_{MONITORING}_{prefix}"

CELERY_QUEUES = (
    Queue(PHASE_DETAIL_CALLBACK_QUEUE, routing_key=PHASE_DETAIL_CALLBACK_QUEUE,
          exchange=Exchange(PHASE_DETAIL_CALLBACK_QUEUE)),
    Queue(MONITORING_QUEUE, routing_key=MONITORING_QUEUE,
          exchange=Exchange(MONITORING_QUEUE)),
)

CELERY_ROUTES = {
    PHASE_DETAIL_CALLBACK: {
        'queue': PHASE_DETAIL_CALLBACK_QUEUE
    },
    MONITORING: {
        'queue': MONITORING_QUEUE
    },
    MONITOR_BASKET: {
        'queue': MONITORING_QUEUE
    },
    MONITOR_ORDER: {
        'queue': MONITORING_QUEUE
    },
    SCHEDULER_PORTFOLIO_MONITORING: {
        'queue': MONITORING_QUEUE
    },
    SCHEDULER_PORTFOLIO_MONITORING_:{
        'queue': MONITORING_QUEUE
    },
    MONITOR_PORTFOLIO_ALERTS: {
        'queue': MONITORING_QUEUE
    },
    SCHEDULER_HOLDING_MONITORING: {
        'queue': MONITORING_QUEUE
    },
    SCHEDULER_HOLDING_MONITORING_: {
        'queue': MONITORING_QUEUE
    },
    MONITOR_HOLDING_THRESHOLD_ALERTS: {
        'queue': MONITORING_QUEUE
    },
    SEND_INVESTMENT_SUCCEEDED_EVENT: {
        'queue': MONITORING_QUEUE
    },
    SEND_WITHDRAWAL_SUCCEEDED_EVENT: {
        'queue': MONITORING_QUEUE
    },
    SEND_LOSS_LIMIT_UPDATED_NOTIFICATION: {
        'queue': MONITORING_QUEUE
    }
}

SENTRY_DSN = os.environ.get("SENTRY_DSN", '')

REBALANCING_BUSINESS_URL = os.environ.get("REBALANCING_BUSINESS_URL", "")
USER_PORTFOLIO_BUSINESS_URL = os.environ.get("USER_PORTFOLIO_BUSINESS_URL", "")
PORTFOLIO_BUSINESS_URL = os.environ.get("PORTFOLIO_BUSINESS_URL", "")
PORTFOLIO_BUSINESS_API_KEY = os.environ.get("PORTFOLIO_BUSINESS_API_KEY", "")

NOTIFY_ON_CALLS = False
NOTIFY_ON_TEAMS = False
ALERT_CODE = "#FF0000"
WARNING_CODE = "#00FF00"
ZENDUTY_URL = os.environ.get("ZENDUTY_URL")
API_TIMEOUT = 5
MS_TEAMS_WEBHOOK_URL = os.environ.get("MS_TEAMS_WEBHOOK_URL",
                                      "https://prod2-23.centralindia.logic.azure.com:443/workflows/d81f7519e90844e59f100c1a09944c9d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=DxzxqN3Qh4ziy54Y-ents9wazAbTFOoQTwFRU9Kt_Y0")

USER_PORTFOLIO_REBALANCE_URL = "/user-portfolio/admin/portfolio/userportfoliorebalance/"
PORTFOLIO_REBALANCE_URL = "/user-portfolio/admin/portfolio/portfoliorebalancetransaction/"
USER_INSTRUCTIONS_URL = "/user-portfolio/admin/portfolio/userinstruction/"
HOLDINGS_URL = "/user-portfolio/admin/holdings/holding/"
TRANSACTIONS_URL = "/user-portfolio/admin/holdings/transaction/"
ORDERS = "/user-portfolio/admin/portfolio/order/"
ORDER_INSTRUCTIONS = "/user-portfolio/admin/portfolio/orderinstruction/"
POSITIONS = "/user-portfolio/admin/holdings/position/"

LOG_REQUEST_ID_HEADER = "HTTP_X_REQUEST_ID"
GENERATE_REQUEST_ID_IF_NOT_IN_HEADER = True

MARKET_PRICER_SERVICE = os.environ.get('MARKET_PRICER_SERVICE')
MARKET_PRICER_CACHE = 'market_pricer_cache'
MARKET_PRICER_CACHE_HOST = os.environ.get('MARKET_PRICER_CACHE_HOST')

if MARKET_PRICER_CACHE_HOST:
    CACHES[MARKET_PRICER_CACHE] = {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": MARKET_PRICER_CACHE_HOST
    }

MONITORING_NOTIFICATION_DELAY = os.environ.get('MONITORING_NOTIFICATION_DELAY', 3)

DATABASE_ROUTERS = ['routers.tenant_router.TenantDatabaseRouter']
TENANTS = ["default", 'ysl']

ENABLE_METRICS = os.getenv("ENABLE_METRICS", "0").lower() in {"1", "true", "yes"}
PROMETHEUS_METRICS_USERNAME = os.environ.get('PROMETHEUS_METRICS_USERNAME', '')
PROMETHEUS_METRICS_PASSWORD = os.environ.get('PROMETHEUS_METRICS_PASSWORD', '')
REBALANCE_BUSINESS_SERVICE_API_KEY=os.environ.get("REBALANCE_BUSINESS_SERVICE_API_KEY", "")
def integrate_metrics():
    global ENABLE_METRICS
    global INSTALLED_APPS
    global MIDDLEWARE
    if ENABLE_METRICS:
        if "django_prometheus" not in INSTALLED_APPS:
            INSTALLED_APPS = ["django_prometheus"] + INSTALLED_APPS
        if "django_prometheus.middleware.PrometheusBeforeMiddleware" not in MIDDLEWARE:
            MIDDLEWARE = ["django_prometheus.middleware.PrometheusBeforeMiddleware"] + MIDDLEWARE
        if "django_prometheus.middleware.PrometheusAfterMiddleware" not in MIDDLEWARE:
            MIDDLEWARE = MIDDLEWARE + ["django_prometheus.middleware.PrometheusAfterMiddleware"]
        if CACHES["default"]["BACKEND"] == "django_redis.cache.RedisCache":
            CACHES["default"]["BACKEND"] = "django_prometheus.cache.backends.redis.RedisCache"
        if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
            DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"

integrate_metrics()
