b"""
Django settings for user_portfolio project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os

from .base import *
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

CSRF_TRUSTED_ORIGINS = [BASE_URL.strip("/"),]

NOTIFY_ON_TEAMS = True

sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[DjangoIntegration()],
    #traces_sample_rate=0.5,
    send_default_pii=True,
    environment="dev"
)

TENANTS = os.environ.get('TENANTS', 'default').split(',')
USER_PORTFOLIO_BUSINESS_URL = "https://user-portfolio-business-service-dev.bridgeweave.net:4448/business/userportfolio"

TENANT_DATABASES = {
    "demo": {
        "ENGINE": 'django.db.backends.postgresql',
        "NAME": os.environ.get("DEMO_USER_PORTFOLIO_DB_NAME", ""),
        "USER": os.environ.get("DEMO_USER_PORTFOLIO_DB_USER", ""),
        "PASSWORD": os.environ.get("DEMO_USER_PORTFOLIO_DB_PASSWORD", ""),
        "HOST": os.environ.get("DEMO_USER_PORTFOLIO_DB_HOST", ""),
        "PORT": os.environ.get("DEMO_USER_PORTFOLIO_DB_PORT", "")
    },
    "ysl": {
        "ENGINE": 'django.db.backends.postgresql',
        "NAME": os.environ.get("YSL_DB_NAME", ""),
        "USER": os.environ.get("YSL_DB_USER", ""),
        "PASSWORD": os.environ.get("YSL_DB_PASSWORD", ""),
        "HOST": os.environ.get("YSL_DB_HOST", ""),
        "PORT": os.environ.get("YSL_DB_PORT", "")
    }
}

DATABASES = {
    'default': {
        "ENGINE": 'django.db.backends.postgresql',
        "NAME": os.environ.get("USER_PORTFOLIO_DB_NAME"),
        "USER": os.environ.get("USER_PORTFOLIO_DB_USER"),
        "PASSWORD": os.environ.get("USER_PORTFOLIO_DB_PASSWORD"),
        "HOST": os.environ.get("USER_PORTFOLIO_DB_HOST"),
        "PORT": os.environ.get("USER_PORTFOLIO_DB_PORT"),
    },
    **TENANT_DATABASES,
}