"""
Django settings for broer-service project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
# pylint:disable=unused-wildcard-import,wildcard-import
from .base import *
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
CSRF_TRUSTED_ORIGINS = [BASE_URL.strip("/"),]

MS_TEAMS_WEBHOOK_URL = ("https://prod2-15.centralindia.logic.azure.com:443/workflows/b91c8e44f6484bc3989fb5da0390037f"
                        "/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0"
                        "&sig=sE9ywmy908ZwaVhtT2tlUAj8Td-sEyhBwPTY_xP9PKw")
NOTIFY_ON_TEAMS = True

sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[DjangoIntegration()],
    #traces_sample_rate=0.1,
    send_default_pii=True,
    environment="prod"
)
