"""
Django settings for broer-service project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
# pylint:disable=unused-wildcard-import,wildcard-import
from .base import *
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
CSRF_TRUSTED_ORIGINS = [BASE_URL.strip("/"),]


MS_TEAMS_WEBHOOK_URL = ("https://prod2-07.centralindia.logic.azure.com:443/workflows/4cc57e9d32344b64918c1d9a920aa365"
                        "/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0"
                        "&sig=ltIFSbVhFGvmHk0kvvGCvy1Xkkuh_ykBRTaUoXHO8xM")
NOTIFY_ON_TEAMS = True

sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[DjangoIntegration()],
    #traces_sample_rate=0.5,
    send_default_pii=True,
    environment="uat"
)

USER_PORTFOLIO_BUSINESS_URL = "https://prometheus-uat.bridgeweave.net/business/userportfolio"


LOGGING = {
    'version': 1,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'request_id': {
            '()': 'log_request_id.filters.RequestIDFilter'
        },
    },
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s.%(msecs)03d] %(levelname)s [%(request_id)s] [%(name)s:%("
                      "lineno)s] %(""message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': ['request_id'],
            'formatter': 'verbose',
        },
        'application': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'when': 'midnight',
            'backupCount': 3,
            'filename': 'logs/user_portfolio.log',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
        'worker': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'when': 'midnight',
            'backupCount': 3,
            'filename': 'logs/worker.log',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console', 'application'],
            'level': 'DEBUG',  # change debug level as appropiate
            'propagate': False,
        },
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console', 'application'],
        },
        'celery': {
            'handlers': ['worker', 'console'],
            'level': 'DEBUG',
        },
        'apps': {
            'handlers': ['console', 'application'],
            'level': 'DEBUG',
        },
        'apps.tenant': {
            'handlers': ['console', 'application'],
            'level': 'INFO',
            'propagate': False,
        }
    }
}
TENANTS=os.environ.get("TENANTS", "default,ysl").split(",")