# Generated by Django 4.2.6 on 2023-10-26 19:17

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioRebalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('allocation_quantity', models.JSONField(default={}, verbose_name='UserAllocationQuantity')),
                ('type', models.CharField(choices=[('initial', 'initial'), ('t0', 't0'), ('t1', 't1')], default='initial', max_length=20)),
                ('current_state', models.CharField(choices=[('processing', 'processing'), ('partially_completed', 'partially_completed'), ('completed', 'completed')], default='processing', max_length=20)),
                ('executed_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'db_table': 'portfolio_rebalance_transaction',
            },
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('portfolio_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active')),
            ],
            options={
                'db_table': 'user_portfolio',
            },
        ),
        migrations.CreateModel(
            name='UserPortfolioRebalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('initial', 'initial'), ('rebalance', 'rebalance')])),
                ('states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('current_state', models.CharField(choices=[('pending', 'pending'), ('partial', 'partial'), ('complete', 'complete')], default='pending', max_length=20)),
                ('rebalance_id', models.IntegerField()),
                ('user_inputs', models.JSONField(default={}, verbose_name='UserInputs')),
                ('cash_ingested', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('transaction_type', models.CharField(choices=[('add', 'add'), ('withdraw', 'withdraw'), ('rebalance', 'rebalance')], max_length=20)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio_rebalances', to='holdings.transaction')),
                ('user_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio_rebalances', to='portfolio.userportfolio')),
            ],
            options={
                'db_table': 'user_portfolio_rebalance',
            },
        ),
        migrations.CreateModel(
            name='UserInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('trade_placement_id', models.IntegerField()),
                ('order_tag', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=20)),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('partial', 'partial'), ('filled', 'filled'), ('cancel', 'cancel')], default='waiting', max_length=20)),
                ('user_portfolio_rebalance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instructions', to='portfolio.portfoliorebalancetransaction')),
            ],
            options={
                'db_table': 'user_instruction',
            },
        ),
        migrations.AddField(
            model_name='portfoliorebalancetransaction',
            name='portfolio_rebalance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_rebalance_transactions', to='portfolio.userportfoliorebalance'),
        ),
    ]
