# Generated by Django 4.2.6 on 2023-10-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliorebalancetransaction',
            name='user_rebalance_json',
            field=models.JSONField(default={}, verbose_name='UserRebalanceJson'),
        ),
    ]
