# Generated by Django 4.2.6 on 2023-10-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliorebalancetransaction_user_rebalance_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinstruction',
            old_name='user_portfolio_rebalance',
            new_name='portfolio_rebalance_transaction',
        ),
    ]
