# Generated by Django 4.2.6 on 2023-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_user_portfolio_rebalance_userinstruction_portfolio_rebalance_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstruction',
            name='trade_placement_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinstruction',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
