# Generated by Django 4.2.6 on 2023-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_userinstruction_trade_placement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstruction',
            name='trade_placement_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
