# Generated by Django 4.2.6 on 2023-11-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_userinstruction_trade_placement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfoliorebalance',
            name='cash_ingested',
            field=models.FloatField(null=True),
        ),
    ]
