# Generated by Django 4.2.6 on 2023-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_userportfoliorebalance_cash_ingested'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='subscription_id',
            field=models.CharField(default='qdfeeeeeeeeee', max_length=100),
            preserve_default=False,
        ),
    ]
