# Generated by Django 4.2.6 on 2023-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_userportfolio_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstruction',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('partial', 'partial'), ('filled', 'filled'), ('cancel', 'cancel'), ('failed', 'failed')], default='waiting', max_length=20),
        ),
    ]
