# Generated by Django 4.2.6 on 2023-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_userinstruction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliorebalance',
            name='metadata',
            field=models.JSONField(default={}, verbose_name='MetaData'),
        ),
    ]
