# Generated by Django 4.2.6 on 2023-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_userportfoliorebalance_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfoliorebalance',
            name='rebalance_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
