# Generated by Django 4.2.6 on 2024-01-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_userportfoliorebalance_rebalance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliorebalancetransaction',
            name='current_state',
            field=models.CharField(choices=[('processing', 'processing'), ('partially_completed', 'partially_completed'), ('completed', 'completed')], default='processing', max_length=50),
        ),
    ]
