# Generated by Django 4.2.6 on 2024-02-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_portfoliorebalancetransaction_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstruction',
            name='reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='portfoliorebalancetransaction',
            name='current_state',
            field=models.CharField(choices=[('processing', 'processing'), ('partially_completed', 'partially_completed'), ('completed', 'completed'), ('retry_enabled', 'retry_enabled'), ('manually_completed', 'manually_completed')], default='processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='userportfoliorebalance',
            name='type',
            field=models.CharField(choices=[('initial', 'initial'), ('rebalance', 'rebalance'), ('reconciliation', 'reconciliation')]),
        ),
    ]
