# Generated by Django 4.2.6 on 2024-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_userinstruction_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='broker',
            field=models.CharField(default='paper_trade', max_length=50),
        ),
    ]
