# Generated by Django 4.2.6 on 2024-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_userportfolio_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliorebalancetransaction',
            name='type',
            field=models.CharField(choices=[('initial', 'initial'), ('t0', 't0'), ('t1', 't1'), ('cash_allocation', 'cash_allocation')], default='initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='userportfoliorebalance',
            name='type',
            field=models.CharField(choices=[('initial', 'initial'), ('rebalance', 'rebalance'), ('reconciliation', 'reconciliation'), ('cash_allocation', 'cash_allocation')]),
        ),
    ]
