# Generated by Django 4.2.6 on 2024-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_portfoliorebalancetransaction_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userportfolio',
            constraint=models.UniqueConstraint(fields=('user_id', 'subscription_id', 'portfolio_id', 'status'), name='unique_user_subscription'),
        ),
    ]
