# Generated by Django 4.2.6 on 2024-07-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_userportfolio_unique_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='deactivated_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
