# Generated by Django 4.2.6 on 2024-08-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_historicaluserportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserportfolio',
            name='proxy',
            field=models.CharField(choices=[('dealer', 'dealer'), ('user', 'user')], default='user'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='proxy',
            field=models.CharField(choices=[('dealer', 'dealer'), ('user', 'user')], default='user'),
        ),
    ]
