# Generated by Django 4.2.6 on 2024-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_historicaluserportfolio_proxy_userportfolio_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliorebalance',
            name='proxy',
            field=models.CharField(choices=[('dealer', 'dealer'), ('user', 'user')], default='user'),
        ),
    ]
