# Generated by Django 4.2.6 on 2024-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_userportfoliorebalance_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliorebalance',
            name='instruction_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
