# Generated by Django 4.2.6 on 2024-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_userportfoliorebalance_instruction_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstruction',
            name='filled_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='portfoliorebalancetransaction',
            name='current_state',
            field=models.CharField(choices=[('processing', 'processing'), ('partially_completed', 'partially_completed'), ('completed', 'completed'), ('retry_enabled', 'retry_enabled'), ('manually_completed', 'manually_completed'), ('skipped', 'skipped')], default='processing', max_length=50),
        ),
    ]
