# Generated by Django 4.2.6 on 2024-09-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_userinstruction_filled_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstruction',
            name='filled_quantity',
            field=models.FloatField(default=0),
        ),
    ]
