# Generated by Django 4.2.6 on 2024-10-07 08:27

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_userinstruction_filled_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_id', models.CharField(max_length=100)),
                ('current_state', models.CharField(choices=[('waiting', 'waiting'), ('monitoring', 'monitoring'), ('complete', 'complete')], default='waiting', max_length=20)),
                ('model_id', models.IntegerField()),
                ('payment_id', models.CharField()),
                ('recommendation_id', models.IntegerField()),
                ('user_allocation', models.JSONField(default=dict)),
                ('cash_ingested', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('profit_target', models.FloatField(null=True)),
                ('profit_target_value', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'basket',
            },
        ),
    ]
