# Generated by Django 4.2.6 on 2024-10-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='model_id',
            field=models.CharField(),
        ),
    ]
