# Generated by Django 4.2.6 on 2024-10-08 07:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_basket_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('trading_symbol', models.CharField()),
                ('buy_price', models.FloatField(null=True)),
                ('sell_price', models.FloatField(null=True)),
                ('current_state', models.CharField(choices=[('waiting', 'waiting'), ('monitoring', 'monitoring'), ('complete', 'complete')], default='waiting', max_length=20)),
                ('amount', models.FloatField(null=True)),
                ('stop_loss', models.FloatField(null=True)),
                ('leverage', models.FloatField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_basket', to='portfolio.basket')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
