# Generated by Django 4.2.6 on 2024-10-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trading_symbol',
            field=models.CharField(max_length=100),
        ),
    ]
