# Generated by Django 4.2.6 on 2024-10-08 09:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_order_trading_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('trade_placement_id', models.IntegerField(null=True, unique=True)),
                ('order_tag', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
                ('filled_quantity', models.FloatField(default=0)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=20)),
                ('value', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('partial', 'partial'), ('filled', 'filled'), ('cancel', 'cancel'), ('failed', 'failed')], default='waiting', max_length=20)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='portfolio.order')),
            ],
            options={
                'db_table': 'order_instruction',
            },
        ),
    ]
