# Generated by Django 4.2.6 on 2024-10-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
