# Generated by Django 4.2.6 on 2024-10-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinstruction',
            name='order_price',
            field=models.FloatField(default=0.0),
        ),
    ]
