# Generated by Django 4.2.6 on 2024-10-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_orderinstruction_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_state',
            field=models.CharField(choices=[('waiting', 'waiting'), ('partial', 'partial'), ('monitoring', 'monitoring'), ('complete', 'complete')], default='waiting', max_length=20),
        ),
    ]
