# Generated by Django 4.2.6 on 2024-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_alter_order_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_type',
            field=models.CharField(choices=[('normal', 'normal'), ('co', 'co')], null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='product_type',
            field=models.CharField(choices=[('mtf', 'mtf'), ('intraday', 'intraday')], null=True),
        ),
    ]
