# Generated by Django 4.2.6 on 2024-10-12 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_basket_basket_type_basket_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='current_state',
        ),
        migrations.AddField(
            model_name='order',
            name='current_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('buy_in_progress', 'buy_in_progress'), ('buy', 'buy'), ('sl_waiting', 'sl_waiting'), ('sl_placed', 'sl_placed'), ('sell', 'sell'), ('skip', 'skip')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
        ),
    ]
