# Generated by Django 4.2.6 on 2024-10-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_remove_order_current_state_order_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinstruction',
            name='order_tag',
            field=models.CharField(max_length=50),
        ),
    ]
