# Generated by Django 4.2.6 on 2024-10-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_alter_orderinstruction_order_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='end_amount',
            field=models.CharField(default=0.0),
        ),
    ]
