# Generated by Django 4.2.6 on 2024-10-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_basket_end_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='end_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='initial_amount',
            field=models.FloatField(null=True),
        ),
    ]
