# Generated by Django 4.2.6 on 2024-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_rename_amount_order_end_amount_order_initial_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('buy_in_progress', 'buy_in_progress'), ('sell_in_progress', 'sell_in_progress'), ('buy', 'buy'), ('sl_waiting', 'sl_waiting'), ('sl_placed', 'sl_placed'), ('sell', 'sell'), ('skip', 'skip')], default='waiting', max_length=20),
        ),
    ]
