# Generated by Django 4.2.6 on 2024-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_alter_order_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='current_state',
            field=models.CharField(choices=[('uninvested', 'uninvested'), ('waiting', 'waiting'), ('monitoring', 'monitoring'), ('complete', 'complete')], default='uninvested', max_length=20),
        ),
    ]
