# Generated by Django 4.2.6 on 2024-10-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_alter_basket_current_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinstruction',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderinstruction',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='portfolio.order'),
            preserve_default=False,
        ),
    ]
