# Generated by Django 4.2.6 on 2024-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_remove_orderinstruction_orders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='profit_target',
            new_name='profit_target_1',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='profit_target_value',
            new_name='profit_target_1_value',
        ),
        migrations.AddField(
            model_name='basket',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='profit_target_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='profit_target_2_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='pt1_hit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='pt1_hit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='pt2_hit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='pt2_hit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_loss_hit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_loss_hit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
