# Generated by Django 4.2.6 on 2024-11-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_rename_profit_target_basket_profit_target_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='profit_target_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='profit_target_1_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='profit_target_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='profit_target_2_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
