# Generated by Django 4.2.6 on 2025-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_alter_basket_profit_target_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinstruction',
            name='order_price',
            field=models.FloatField(null=True),
        ),
    ]
