# Generated by Django 4.2.6 on 2025-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_alter_orderinstruction_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserportfolio',
            name='proxy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='proxy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userportfoliorebalance',
            name='proxy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
