# Generated by Django 4.2.6 on 2025-01-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_historicaluserportfolio_proxy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserportfolio',
            name='proxy_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='proxy_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userportfoliorebalance',
            name='proxy_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
