# Generated by Django 4.2.6 on 2025-01-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0044_alter_historicaluserportfolio_proxy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='broker',
            field=models.CharField(blank=True, choices=[('axis', 'axis'), ('zerodha', 'zerodha'), ('lkp', 'lkp'), ('paper_trade', 'paper_trade'), ('pl', 'pl'), ('jm', 'jm'), ('hdfc', 'hdfc'), ('bnr', 'bnr'), ('demo', 'demo'), ('almondz', 'almondz'), ('jm_pro', 'jm_pro')], null=True),
        ),
    ]
