# Generated by Django 4.2.6 on 2025-03-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_add_aua_initial_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstruction',
            name='asm_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinstruction',
            name='asm_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='broker',
            field=models.CharField(blank=True, choices=[('axis', 'axis'), ('zerodha', 'zerodha'), ('lkp', 'lkp'), ('paper_trade', 'paper_trade'), ('pl', 'pl'), ('jm', 'jm'), ('hdfc', 'hdfc'), ('bnr', 'bnr'), ('demo', 'demo'), ('emkay', 'emkay'), ('almondz', 'almondz'), ('jm_pro', 'jm_pro')], null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserportfolio',
            name='expected_investment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
