# Generated by Django 4.2.6 on 2025-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0047_userinstruction_asm_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstruction',
            name='asm_consent',
            field=models.BooleanField(null=True),
        ),
    ]
