# Generated by Django 4.2.6 on 2025-04-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0048_alter_userinstruction_asm_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliorebalance',
            name='rebalance_strategy',
            field=models.CharField(choices=[('complete', 'COMPLETE'), ('partial', 'PARTIAL')], max_length=255, null=True),
        ),
    ]
