# Generated by Django 4.2.6 on 2025-07-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0049_userportfoliorebalance_rebalance_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinstruction",
            name="type",
            field=models.CharField(
                choices=[("normal", "normal"), ("reconcile", "reconcile")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="broker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("axis", "axis"),
                    ("zerodha", "zerodha"),
                    ("lkp", "lkp"),
                    ("paper_trade", "paper_trade"),
                    ("pl", "pl"),
                    ("jm", "jm"),
                    ("hdfc", "hdfc"),
                    ("bnr", "bnr"),
                    ("demo", "demo"),
                    ("emkay", "emkay"),
                    ("almondz", "almondz"),
                    ("jm_pro", "jm_pro"),
                    ("symphony", "symphony"),
                    ("hdfcir", "hdfcir"),
                ],
                null=True,
            ),
        ),
    ]
