# Generated by Django 4.2.6 on 2025-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0050_orderinstruction_type_alter_basket_broker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderinstruction",
            name="type",
            field=models.CharField(
                choices=[
                    ("normal", "normal"),
                    ("reconcile", "reconcile"),
                    ("square_off", "square_off"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
