# Generated by Django 4.2.6 on 2025-07-21 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0051_alter_orderinstruction_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderinstruction",
            old_name="type",
            new_name="source",
        ),
    ]
