# Generated by Django 4.2.6 on 2025-07-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0052_rename_type_orderinstruction_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderinstruction",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "manual"),
                    ("reconcile", "reconcile"),
                    ("square_off", "square_off"),
                    ("margin_call", "margin_call"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
