# Generated by Django 4.2.6 on 2025-07-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_alter_orderinstruction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliorebalancetransaction',
            name='instruction_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
