# Generated by Django 4.2.6 on 2025-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0055_portfoliorebalancetransaction_instruction_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="broker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("axis", "axis"),
                    ("zerodha", "zerodha"),
                    ("lkp", "lkp"),
                    ("paper_trade", "paper_trade"),
                    ("pl", "pl"),
                    ("jm", "jm"),
                    ("hdfc", "hdfc"),
                    ("bnr", "bnr"),
                    ("demo", "demo"),
                    ("emkay", "emkay"),
                    ("almondz", "almondz"),
                    ("jm_pro", "jm_pro"),
                    ("symphony", "symphony"),
                    ("hdfcir", "hdfcir"),
                    ("ysl", "ysl"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="product_type",
            field=models.CharField(
                choices=[("mtf", "mtf"), ("intraday", "intraday"), ("cnc", "cnc")],
                null=True,
            ),
        ),
    ]
