# Generated by Django 4.2.6 on 2025-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0056_alter_basket_broker_alter_basket_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserportfolio",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[("mtf", "mtf"), ("intraday", "intraday"), ("cnc", "cnc")],
                default="cnc",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[("mtf", "mtf"), ("intraday", "intraday"), ("cnc", "cnc")],
                default="cnc",
                null=True,
            ),
        ),
    ]
