# Generated by Django 4.2.6 on 2025-08-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0057_historicaluserportfolio_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserportfolio",
            name="strategy",
            field=models.CharField(
                blank=True,
                choices=[("rebalance", "rebalance"), ("one_time", "one_time")],
                default="rebalance",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userportfolio",
            name="strategy",
            field=models.CharField(
                blank=True,
                choices=[("rebalance", "rebalance"), ("one_time", "one_time")],
                default="rebalance",
                null=True,
            ),
        ),
    ]
