# Generated by Django 4.2.6 on 2025-08-21 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0058_historicaluserportfolio_strategy_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userportfolio",
            name="unique_user_subscription",
        ),
    ]
