# Generated by Django 4.2.6 on 2025-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0059_remove_userportfolio_unique_user_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinstruction",
            name="leverage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
