# Generated by Django 4.2.6 on 2025-08-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0060_userinstruction_leverage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("mtf", "mtf"),
                    ("intraday", "intraday"),
                    ("equity", "equity"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserportfolio",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtf", "mtf"),
                    ("intraday", "intraday"),
                    ("equity", "equity"),
                ],
                default="equity",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userportfolio",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtf", "mtf"),
                    ("intraday", "intraday"),
                    ("equity", "equity"),
                ],
                default="equity",
                null=True,
            ),
        ),
    ]
