# Generated by Django 4.2.6 on 2025-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0061_alter_basket_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='broker',
            field=models.CharField(blank=True, choices=[('axis', 'axis'), ('zerodha', 'zerodha'), ('lkp', 'lkp'), ('paper_trade', 'paper_trade'), ('pl', 'pl'), ('jm', 'jm'), ('hdfc', 'hdfc'), ('bnr', 'bnr'), ('demo', 'demo'), ('emkay', 'emkay'), ('almondz', 'almondz'), ('jm_pro', 'jm_pro'), ('symphony', 'symphony'), ('hdfcir', 'hdfcir'), ('ysl', 'ysl'), ('mandot', 'mandot')], null=True),
        ),
    ]
