# Generated by Django 4.2.6 on 2025-09-23 20:15

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0062_alter_basket_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_id', models.CharField(max_length=100)),
                ('phase_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='processing', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('portfolio_rebalance_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_callback', to='portfolio.portfoliorebalancetransaction')),
            ],
            options={
                'db_table': 'phase_callback_log',
            },
        ),
    ]
