# Generated by Django 4.2.6 on 2026-03-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0063_phasecallbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliorebalance',
            name='cash_carry_forward',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userportfoliorebalance',
            name='reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
