# Generated by Django 4.2.6 on 2026-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0064_userportfoliorebalance_cash_carry_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstruction',
            name='retry_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
