# Generated by Django 4.2.6 on 2026-04-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0065_userinstruction_retry_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstruction',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
